URL_MAIN_PART=https://idproofing-api.wr.eu.identity-prod.idemia.io:443/gips/v1;
API_KEY=p4QOhaIH2ePZ0HUasUThvLBTwP0YMhFd;

keycloak:
  realm: serr
  auth-server-url: http://localhost:8180/auth
  resource: octo-poc-idemia
  public-client: false
  bearer-only: true
